[package]
name = "code"
version = "0.1.0"
authors = ["Huon Wilson <dbau.pp+github@gmail.com>"]

[dependencies]
simple_parallel = "0.3"
serde = "0.6"
serde_json = "0.6"
rand = "0.3"
image = "0.6"
scoped_threadpool = "0.1"
